# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputLayout = QtWidgets.QHBoxLayout()
        self.inputLayout.setObjectName("inputLayout")
        self.lineEdit1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit1.setObjectName("lineEdit1")
        self.inputLayout.addWidget(self.lineEdit1)
        self.lineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit2.setObjectName("lineEdit2")
        self.inputLayout.addWidget(self.lineEdit2)
        self.verticalLayout.addLayout(self.inputLayout)
        self.operationsLayout = QtWidgets.QHBoxLayout()
        self.operationsLayout.setObjectName("operationsLayout")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setObjectName("btnAdd")
        self.operationsLayout.addWidget(self.btnAdd)
        self.btnSub = QtWidgets.QPushButton(self.centralwidget)
        self.btnSub.setObjectName("btnSub")
        self.operationsLayout.addWidget(self.btnSub)
        self.btnMul = QtWidgets.QPushButton(self.centralwidget)
        self.btnMul.setObjectName("btnMul")
        self.operationsLayout.addWidget(self.btnMul)
        self.btnDiv = QtWidgets.QPushButton(self.centralwidget)
        self.btnDiv.setObjectName("btnDiv")
        self.operationsLayout.addWidget(self.btnDiv)
        self.verticalLayout.addLayout(self.operationsLayout)
        self.calculateLayout = QtWidgets.QHBoxLayout()
        self.calculateLayout.setObjectName("calculateLayout")
        self.btnCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalculate.setEnabled(False)
        self.btnCalculate.setObjectName("btnCalculate")
        self.calculateLayout.addWidget(self.btnCalculate, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.calculateLayout)
        self.labelResult = QtWidgets.QLabel(self.centralwidget)
        self.labelResult.setObjectName("labelResult")
        self.verticalLayout.addWidget(self.labelResult)
        self.listHistory = QtWidgets.QListWidget(self.centralwidget)
        self.listHistory.setObjectName("listHistory")
        self.verticalLayout.addWidget(self.listHistory)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.btnAdd.setText(_translate("MainWindow", "+"))
        self.btnSub.setText(_translate("MainWindow", "-"))
        self.btnMul.setText(_translate("MainWindow", "*"))
        self.btnDiv.setText(_translate("MainWindow", "/"))
        self.btnCalculate.setText(_translate("MainWindow", "Рассчитать"))
        self.labelResult.setText(_translate("MainWindow", "Результат"))
