# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit1.setGeometry(QtCore.QRect(40, 30, 141, 31))
        self.lineEdit1.setObjectName("lineEdit1")
        self.lineEdit2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit2.setGeometry(QtCore.QRect(210, 30, 141, 31))
        self.lineEdit2.setObjectName("lineEdit2")
        self.btnAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(40, 80, 61, 31))
        self.btnAdd.setObjectName("btnAdd")
        self.btnSub = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSub.setGeometry(QtCore.QRect(110, 80, 61, 31))
        self.btnSub.setObjectName("btnSub")
        self.btnMul = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnMul.setGeometry(QtCore.QRect(180, 80, 61, 31))
        self.btnMul.setObjectName("btnMul")
        self.btnDiv = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDiv.setGeometry(QtCore.QRect(250, 80, 61, 31))
        self.btnDiv.setObjectName("btnDiv")
        self.labelResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(40, 140, 311, 31))
        self.labelResult.setObjectName("labelResult")
        self.listHistory = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listHistory.setGeometry(QtCore.QRect(40, 190, 311, 80))
        self.listHistory.setObjectName("listHistory")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.btnAdd.setText(_translate("MainWindow", "+"))
        self.btnSub.setText(_translate("MainWindow", "-"))
        self.btnMul.setText(_translate("MainWindow", "*"))
        self.btnDiv.setText(_translate("MainWindow", "/"))
        self.labelResult.setText(_translate("MainWindow", "Результат"))
